### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by tallica** [team-inbox/inbox-reborn#13]
How can I build a Firefox addon based on master branch? Current "Inbox in Gmail" addon is very outdated.

**Comment by jonrandy** [comment]
If things are still the same as the last time I played with addons - it shouldn't be much more complex than zippig some files and renaming the zipped file. Maybe we can add a build script here? I can take a look myself later if I can find some time

**Comment by jonrandy** [comment]
[inboxreborn.zip](https://github.com/team-inbox/inbox-reborn/files/5107385/inboxreborn.zip)

Give this a try - you'll need to set `xpinstall.signatures.required` to `false` in Firefox's config (`about:config`) first, then use "Install Add-on From File..." on the ⚙ menu on the addons page

**Comment by jonrandy** [comment]
I've addressed this with a small change, and some instructions in the ReadMe - https://github.com/team-inbox/inbox-reborn/pull/14 - hopefully these changes will be merged soon

**Comment by tallica** [comment]
@jonrandy Thank you :) It worked!

**Comment by g60madman** [comment]
This has been merged into the main code. Closing this out.

@jonrandy thanks for the work!!
