### ISSUE TITLE
Bundles no longer working 

### ISSUE THREAD

**Issue by SharonPerp** [team-inbox/inbox-reborn#15]
Hi, my bundles been working for some time now and I finally went and redid all the settings per instructions here but no go. Is it just me? Don't think I've changed anything - still running Catalina 10.15.6.  TIA

**Comment by g60madman** [comment]
Sorry for the delay, pull down the newest code I just merged in some changes from @jonrandy

https://github.com/team-inbox/inbox-reborn/pull/16

If this solves the problem let me know and I will close this out.

**Comment by g60madman** [comment]
@SharonPerp is bundling still not working? Let me know.

**Comment by SharonPerp** [comment]
So, so, sorry for ridiculously late response. Bundles! are working, but I
do get the following error message upon installation:

[image: image.png]

I've disabled previous version but didn't want to install it until it
looked like everything was going to be ok. Can I just ignore these errors?

Thanks!

**Comment by g60madman** [comment]
Sorry for the delay I am not seeing the image.png file you are seeing. Let me know.

**Comment by SharonPerp** [comment]
Actually, things seem to be working wonderfully again! I actually spent a
long LONG day clearing out my inbox (thousands!) and redoing filters and
labels, maybe that helped.

But, right now I see all my bundles, nicely color-coded, both in the
sidebar and message list, so I think it's best to ignore the installation
error message completely.

Amazing what a difference it makes, THANK YOU!

**Comment by jonrandy** [comment]
You can safely ignore the installation error. It is a related to a small change we made so that the extension works both on Firefox and Chrome (I'm guessing you're using the latter - as that's where you'd see the error)

**Comment by SharonPerp** [comment]
Got it. Thanks again!

**Comment by jonrandy** [comment]
You're welcome! 

@g60madman I think we can close this now
