### ISSUE TITLE
Compose button misbehaving

### ISSUE THREAD

**Issue by jarekwg** [team-inbox/inbox-reborn#20]
Compose button has migrated to the LHS of the page.
![image](https://user-images.githubusercontent.com/5036488/114358220-067adb00-9bb6-11eb-945b-f82ea650b2d3.png)

Seems latest gmail has moved the button, and unlinked it from inbox-reborn's compose button in the bottom right.

e: for reference, here's what it looks like skinless:
![image](https://user-images.githubusercontent.com/5036488/114481468-ebf14200-9c47-11eb-906e-92f91c38ee66.png)

**Comment by jonrandy** [comment]
Hmmmm... not for me it hasn't - on neither of my 2 accounts. Maybe they're AB testing an upcoming change. I guess we'll need to fix stuff if changes over completely

**Comment by jarekwg** [comment]
Hmm, yeah I'm not seeing it on my other gmail account.. fun!

**Comment by g60madman** [comment]
Nor me?

**Comment by g60madman** [comment]
@jarekwg can you try and install from the Google Chrome Store and see if it happens again?

https://chrome.google.com/webstore/detail/inbox-reborn-theme-for-gm/bkphmihkdbdgedlaflnkhnmnmibffomf

**Comment by jarekwg** [comment]
Ooh, nice to see it's back in the chrome web store!

But nope, 0.5.9.2, doesn't address this either. Working compose button is still in the top left, with both extension enabled and disabled. This theme's big red compose button in the bottom right gets rendered, but is not functional. Blue reminder button above it doesn't do anything either.

**Comment by g60madman** [comment]
@jarekwg what browser are you using?

**Comment by jarekwg** [comment]
Chrome, Version 90.0.4430.72 (Official Build) beta (x86_64)
I have work and person gmails open in two separate tabs -- one has the compose button shifted to top left, other has it in bottom right (and works with inborn theme).
As you said, this is likely some AB testing, but happy to give you more info if you need.

**Comment by g60madman** [comment]
@jarekwg What if you install the standard version of Chrome and not the beta? This is the version I am running on my Mac, and Windows box.

90.0.4430.85 (Official Build) (x86_64)

**Comment by g60madman** [comment]
@jarekwg One other thing to check is what version of Gmail they are loading you. If you turn off the extension through chrome://extension and then inspect the page look at the following section of code, I am guessing this is the version of Gmail I have, I wonder if yours is different?

![image](https://user-images.githubusercontent.com/1558465/115998119-0f4eb200-a5a3-11eb-9583-42eecf35b019.png)

**Comment by jarekwg** [comment]
hrm, `data-new-gr-cs-s-loaded` isn't present in the source. The block you're referring to exists, and all of its other keys are present, except that one. Further, what is present, is identical between my two tabs.
```
<body
  jscontroller="hS6RLb"
  jsmodel="utMpr"
  jsaction="rcuQ6b:rcuQ6b;A59Jsf:aeO1Sd;RW0A4:WBopzd;FwQykc:k0aXUd;LPBdz:LCjO0c;jrvfrd:PB0Csf;FGHbk:Nx2Sl;qNGYPc:LEY81c;JpvSPb:EL4Jr;Aeulrb:nixEK;YweIdb:.CLIENT;iE7Vzc:.CLIENT;v9KJX:.CLIENT;RzaMQe:.CLIENT;Jdbq1c:.CLIENT;IRuwXc:.CLIENT;ORuuO:.CLIENT;Ly2fm:.CLIENT"
  class="aAU"
  jslog="38365; u014N:xr6bB; 16:WzZd"
  data-awr-sg-installed="true"
>
```

**Comment by jarekwg** [comment]
There's been a new development: My other mail tab has also migrated the compose button to the top left now. I'm guessing they're broadening the rollout? Or it's a caching game.

Dunno about edge (I'm on osx), and only version of Chrome I've been running is that beta version i described above.
I just had a look on firefox now though and both my gmails have the compose button in the top left too.

**Comment by g60madman** [comment]
@jarekwg Sounds like Google is rolling something else out we may need to deal with it when it comes. Believe it or not, you can install Edge on OSX 🤣  of course it's still just Chrome just MS's baby.

**Comment by arormoser** [comment]
I'm having the same problem
![image](https://user-images.githubusercontent.com/8503100/116407555-4376dc80-a808-11eb-8f08-d263a726cc60.png)

**Comment by g60madman** [comment]
@arormoser we are aware of the issue but it's not affecting all users yet so I don't know how easy it will be to implement a temp fix. Since I don't see the issue I can't test the code against it. It looks like only a handful of users are getting updated to a new rollout of Gmail and until it affects one of the developers we won't' be able to fix it.

**Comment by gdubja** [comment]
@g60madman this started last week for me but i thought you guys would be on top of it. i have one of the oldest gmail accounts which is why this stuff normally gets pushed out to me before others. my wife isn't seeing it yet. 

strangely, they abandoned hangouts yesterday and replaced it with "chat." and it doesn't behave as nicely in this extension anymore. i can't pop out a chat into its own window any longer.

**Comment by gdubja** [comment]
oh, and they also updated the icons

![image](https://user-images.githubusercontent.com/84877720/119730993-3eb73f80-be2b-11eb-9117-c09ba745d44c.png)

**Comment by gdubja** [comment]
and now they've removed the grouping of the email by date: today, yesterday, earlier this week, earlier this month, april, last year, etc. 
![image](https://user-images.githubusercontent.com/84877720/119731704-1e3bb500-be2c-11eb-9993-71fbe33afd1d.png)

**Comment by deepfriedfilth** [comment]
@g60madman @jonrandy you can (temporarily) opt in to the new chat via Settings > Chat and Meet > Chat > Google Chat and you'll be able to see the new compose button near the top of the left side bar...

I've begun messing around in dev tools to simply reposition, but it unfortunately is seems very much tied to the left bar, so this might require a little bit of R&D to remedy, at least more than I have the effort to dig into immediately 😴

Also want to note that bundling is still working as it should after switching for me, and the icons seem unaffected. ¯\_(ツ)_/¯

**Comment by g60madman** [comment]
@deepfriedfilth yup see the issue now with the settings. I will see if I can take some time to mess with it. Been really busy as work is getting back to normal.

**Comment by drafie** [comment]
Same issue here - compose button no longer works, seems directly related to the Chat feature for me.

**Comment by arormoser** [comment]
Any news?

**Comment by deepfriedfilth** [comment]
Quick n dirty solution (Firefox only ATM) until I get s'more sleep and clean up a few things on my `dev` branch: https://github.com/deepfriedfilth/inbox-reborn/commit/48ad4f25c685cf8ebff35207047aeeb90e91570b

I'll submit a proper PR when I feel it's there!
