### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by shank-eric** [team-inbox/inbox-reborn#22]
I noticed some renewed activity here recently and thought I would cross-post the same offer here that I posted on the original repo: https://github.com/boukestam/inbox-in-gmail/issues/106.  

Since my post, I've continued to make adjustments and also implemented some new features: 
* using preview pane to expand emails inline
* expanding bundles inline
* dark mode compatability

Again, the changes are very significant and I've been tailoring things more and more to my own personal use, so I'd be hesitant to merge it without confirmation that I haven't broken anything critical.  On the other hand, I'd be happy to help contribute to a project that is crucial to my daily use of gmail, both professionally and personally.

**Comment by g60madman** [comment]
If you see things you would like to do simply fork the main repo and then do a pull request with the changes and also update the readme. We are always open to having users develop and make changes!

**Comment by shank-eric** [comment]
Alright, it's basically a full rewrite of the repo, but I'll open it up.

**Comment by g60madman** [comment]
@shank-eric It might make sense to make small changes at a time so it's not all or nothing. Also if you can integrate the changes in the main drop-down for dark mode etc. that would be ideal so users have the ability to turn on or off features.

![image](https://user-images.githubusercontent.com/1558465/119177242-48a30200-ba29-11eb-9a43-405fcaec06f4.png)

**Comment by shank-eric** [comment]
One of the very first things I did was to do the full conversion to webpack, so unfortunately all of my changes are predicated on a restructuring of the repo as a whole.  

The dark mode feature is based on enabling the dark mode theme in gmail, so it should already be something users can choose to turn on/off.
