### ISSUE TITLE
Reminder button options

### ISSUE THREAD

**Issue by Madis0** [team-inbox/inbox-reborn#31]
As Google's reminder systems are spread across services, I suggest the button to:

1. Open Google Keep in the built-in sidebar
2. Open Google Tasks in the built-in sidebar
3. Create a new "Reminder" mail (like now)
4. Hide the button altogether

The first two options would be nice if the user otherwise would hide the sidebar, so that would save the screen space like 50px from the right to just use a floating button instead :D

**Comment by deepfriedfilth** [comment]
Sounds like you have the technical knowledge to perhaps come up with a solution yourself and submit a PR.. the repo is certainly open to collaboration/code contributions!
