### ISSUE TITLE
Header color swaps stopped doing the thing

### ISSUE THREAD

**Issue by deepfriedfilth** [team-inbox/inbox-reborn#34]
Just noticed the header wasn't returning to blue after diving into my inboxes. Opened a new instance in Chrome after that happened in Firefox to confirm, and yessir, the header color swapping for Inbox, Starred, Snoozed, et al is b0rked.

I'll take a peek this weekend/next week and see what's changed.

**Comment by jeff-hykin** [comment]
came here to report this as well.

Looks like the CSS selector `.nH.w-asV.aiw[pageTitle="inbox"]` no longer works because `pageTitle="inbox"` is no longer a thing. Which means its going to be an annoying Javascript check-and-set to get the functionality back.

**Comment by jonrandy** [comment]
I've fixed it - was quite trivial - just two CSS selectors needed to change, plus a call to `handleHashChange` on start-up. Will test properly and submit PR later

**Comment by jonrandy** [comment]
PR #35

**Comment by jonrandy** [comment]
Just noticed the compose button has gone again... grrrr. No time to look at that now though

**Comment by jonrandy** [comment]
Fixed :)

**Comment by jeff-hykin** [comment]
Thanks @jonrandy !
