### ISSUE TITLE
Travel, Trips: Icon

### ISSUE THREAD

**Issue by jonrandy** [team-inbox/inbox-reborn#36]
Since "Travel" and "Trips" are system labels (user cannot define them as visible in GMail, and also cannot apply them) - does it make sense to expand our logic for displaying the Travel icon to maybe include any label that includes any of the words 'trip', 'trips', or 'travel'? Currently, as far as I can see, this icon will never be visible. 

What is interesting is that behind the scenes, GMail is still auto-categorising emails into these labels, but there is no actual way to have the label 'visible'. A search for 'label:travel' works though

(I actually already have the required changes completed in a branch)

**Comment by g60madman** [comment]
I wouldn't be opposed to this feature. If you have the time I am been so freaking busy lately with work I barely even check my Gmail from a computer anymore as it's blocked at work and at home, the last thing I want to do is sit in front of a computer.

**Comment by jonrandy** [comment]
PR #38

**Comment by jonrandy** [comment]
Closing this as it has been merged
