### ISSUE TITLE
heading color: blue -> gray

### ISSUE THREAD

**Issue by heavy-baby** [team-inbox/inbox-reborn#37]
![2021-11-06 8 07 46](https://user-images.githubusercontent.com/59328555/140587890-1026befb-f5e6-47a8-b00e-deb98faa15ed.png)
at Inbox tab, i love blue instead of gray .

**Comment by jonrandy** [comment]
Please update to the latest version, this was a problem that is now fixed

**Comment by heavy-baby** [comment]
thank you.
but chrome web store version is still 0.5.9.2.
i'm waiting for update.

**Comment by g60madman** [comment]
@heavy-baby jonrandhy has been adding a lot of content to the plugin. Once it's completed I will repost to the web store assuming Google accepts it again. For now, download the zip.
