### ISSUE TITLE
Compose icon issue when using new Google Chat turned on

### ISSUE THREAD

**Issue by g60madman** [team-inbox/inbox-reborn#39]
If you turn on the new Google Chat
![image](https://user-images.githubusercontent.com/1558465/140617967-5e684e6f-67f8-4fc0-ac0f-812b1ecd3aa1.png)

The compose button is messed up
![image](https://user-images.githubusercontent.com/1558465/140617998-ee08666f-ed03-4d7f-818e-31a2d20d66b9.png)

This looks to be the only issue we need to correct before I submit it back to the Web Store

**Comment by jonrandy** [comment]
I am unable to reproduce this - tried every combination of options on both Firefox and Chrome

**Comment by g60madman** [comment]
@jonrandy weird I am having the problem both on Windows 10 Pro and Ubuntu 20.04 with the current version of Chrome with the Google Chat. With the Classic Hangouts, all is well in the world. I will go ahead and work on pushing it up to the Web Store. If we see more users with the issue we can deal with it at that time.
