### ISSUE TITLE
Title bar turned grey instead of blue

### ISSUE THREAD

**Issue by LLI-inc** [team-inbox/inbox-reborn#41]
I just noticed a few days ago that the title bar has turned grey instead of blue on all my chrome browsers. Any ideas why? (I didn't realize how much I liked the blue until it disappeared)! 

![image](https://user-images.githubusercontent.com/46686069/141308805-2e00754c-16e7-4eb2-8327-cd55ec3d49a1.png)

**Comment by g60madman** [comment]
This has been resolved with the newer code if you download the source code. I am going to try and resubmit to Google today

**Comment by LLI-inc** [comment]
Wow, nice job. And I love the subtle 3D effect on the text on the left.  One thing though... some of the text in the menu on the left and around the top has turned white - making it almost invisible. 

![image](https://user-images.githubusercontent.com/46686069/141650248-dba2bb95-ca5b-4027-8cc2-7d3370155834.png)

![image](https://user-images.githubusercontent.com/46686069/141650243-3437d222-1306-4158-ab12-09723cb7b9a7.png)

**Comment by g60madman** [comment]
What browser are you using? This is not happing in chrome.

![image](https://user-images.githubusercontent.com/1558465/141691277-a512b6ed-02fc-438f-919e-e677ea5ab612.png)

**Comment by LLI-inc** [comment]
I wrote in while using Vivaldi. But now that you've brought this up, I found out it's doing the same thing in my copy of Brave & CHROME itself. The only browser it works right on, strangely enough, is Microsoft Edge (which I never use).  

It could be something in my configuration or maybe a conflict with another mail theme I was trying out in those browsers.

**Comment by deepfriedfilth** [comment]
@LLI-inc I'd lean towards it being a conflict, as I submitted the original issue (#34) with plans to fix but one of the other devs beat me to it, and I'm not seeing any of the white text from your screenshot in Chrome or Firefox ¯\\\_(ツ)_/¯
