### ISSUE TITLE
Firefox Addons Page Version Outdated

### ISSUE THREAD

**Issue by tilden** [team-inbox/inbox-reborn#43]
The version of this extension on the Firefox Addons site is outdated, necessitating the use of Firefox Developer Edition plus the unsigned extension bundle installation workaround as noted in the readme.

Would it be possible to update the Firefox Addons site version of this extension?

**Comment by g60madman** [comment]
@tilden Since most Gmail users are Chrome users or Edge users I never opted to repost to the Firefox store as it's just one more place to release the extension.

@boukestam can you update the Firefox extension with the newest edition since you set this up in the store?

**Comment by fgblomqvist** [comment]
> Since most Gmail users are Chrome users or Edge user

This is most definitely not true 😢

**Comment by tilden** [comment]
@fgblomqvist 

FWIW, I've found another bundling extension for Gmail that _does_ work with Firefox -- you might want to give it a try: https://www.inboxymail.com/

**Comment by fgblomqvist** [comment]
I'm actually only just interested in the theming/button placement of inbox (I don't like the full width of Gmail), but I'll check it out. Thanks!

**Comment by jonrandy** [comment]
@joeytroy @boukestam I'd be happy to update the Firefox one. Would it be better to set up a "Team Inbox" account on the Firefox add-ons?

**Comment by joeytroy** [comment]
@jonrandy Sure man if you want to post you are more than welcome!

**Comment by SixParQuatre** [comment]
I'd like to bump this issue again - I'm a firefox user as well:  the signature workaround doesn't work with normal Firefox and I don't see myself changing to dev version for this..
The other firefox extension that did something similar has finally stopped working and isn't being maintained so having a legit version of yours would be amazing..
My knowledge of firefox dev is close to 0 but let me know if and how I can help!

**Comment by jonrandy** [comment]
Trying to re-upload new one on a new account, but add-on id clashes with existing one, so no go. Can @boukestam give us access or take it down or something? Otherwise we have to change the id... not a huge deal, but just makes publishing slightly more of a PITA

**Comment by joeytroy** [comment]
@jonrandy I am not sure @boukestam is still working on the project anymore. I would say if we don't hear from him maybe just resubmit it to the store if you are good with maintaining it.

**Comment by joeytroy** [comment]
Sounds good! Can also update the readme to the Firefox link as well once it's approved?

**Comment by jonrandy** [comment]
Awaiting review...

**Comment by jonrandy** [comment]
Review approved 🎉

Firefox version is live at: https://addons.mozilla.org/en-GB/firefox/addon/inbox-reborn-theme-gmail/

**Comment by joeytroy** [comment]
@tilden 

Is the plugin working as expected now on FireFox?

**Comment by SixParQuatre** [comment]
Yes, it does! I'm sorry for the delay in answering:) Thanks a lot to yall again !
