### ISSUE TITLE
Compose Button Missing

### ISSUE THREAD

**Issue by oscarwong67** [team-inbox/inbox-reborn#45]
Using Chrome Version 98.0.4758.102 (Official Build) (x86_64) on MacOS 11.5.2 (but I have noticed the same behavior on my windows machine as well), I haven't been seeing the Compose Button lately.

<img width="114" alt="Screen Shot 2022-02-22 at 3 11 26 PM" src="https://user-images.githubusercontent.com/12058020/155228198-ce17a6a3-cdd1-4531-9b95-79f9186b1394.png">

Unsure if relevant, but these console logs appear in the Chrome Dev tools:
<img width="689" alt="Screen Shot 2022-02-22 at 3 12 59 PM" src="https://user-images.githubusercontent.com/12058020/155228402-334285e6-98a9-48df-bdf4-27e543f70315.png">

**Comment by funspotwebmaster** [comment]
I also have this issue. Any solution?

**Comment by phicau** [comment]
I have fixed it here: https://github.com/phicau/inbox-reborn

**Comment by oscarwong67** [comment]
oh thanks @phicau ! I hope we can get a maintainer to look at it, it's a pretty short PR too

**Comment by g60madman** [comment]
@oscarwong67 @phicau 
I will take a look at this soon. I am running on Windows and see no issues currently but will do some testing to make sure this works OK on Linux and Windows before pushing up to Google.

**Comment by jonrandy** [comment]
I'm currently having no issues with the current version, on Firefox and
Chrome - on both Linux and Mac.

Weird.

**Comment by phicau** [comment]
Yes, weird, here is more info from my side.
I am basically experiencing the same issues as @oscarwong67 but with Chrome Version 99.0.4844.51 (Official Build - arm64) and Inbox Reborn theme for Gmail™ Version 0.5.9.8 (ID bkphmihkdbdgedlaflnkhnmnmibffomf) on MacOS 12.0.1

The changes that I made fix both issues, at least for me.

**Comment by funspotwebmaster** [comment]
I found that another extension was interfering. In my case it was V7 Gmail Zoom. When I disabled this extension and did a hard refresh of the page (CTRL+F5) the compose button returned!

**Comment by funspotwebmaster** [comment]
Spoke too soon. Issue has returned despite disabling other V7 Gmail Zoom extension.

<img width="698" alt="Missing Compose Button" src="https://user-images.githubusercontent.com/100800359/159955299-edf6ed7f-9097-419c-870b-ef0c9155c7e4.PNG">

**Comment by gnemtzov** [comment]
I have the same issue on Crome 102.0.5005.61, Mac 12.2.1. Disabling other extensions or reinstalling this one does not help
 
<img width="293" alt="Screenshot 2022-06-03 at 08 41 00" src="https://user-images.githubusercontent.com/89066738/171801236-ad39e5bd-8bbc-4724-a028-942fbde98074.png">

**Comment by jonrandy** [comment]
Interesting - I'm on Mac with same chrome version and I don't have the problem

**Comment by gnemtzov** [comment]
The issue appeared (i.e. the button disappeared :) never to be seen again) after opening and closing the calendar side panel and resizing/refreshing the page (in attempts to solve the problem with the compose and reminder buttons not repositioning on open/close of the calendar side panel)

**Comment by phicau** [comment]
@gnemtzov you can try with this version https://github.com/phicau/inbox-reborn
It is still working for me after experiencing the same problem using the official version from the chrome web shop

**Comment by gnemtzov** [comment]
Thanks @phicau but how do I install it? 
It says:
Installing
Chrome & Microsoft Edge
The extension has been updated 12/21/21 to version 0.5.9.8. It can be added through the following link
https://chrome.google.com/webstore/detail/inbox-reborn-theme-for-gm/bkphmihkdbdgedlaflnkhnmnmibffomf
I tried the link (which seems to be the official chrome web shop version) and it didn't change anything

**Comment by gnemtzov** [comment]
@phicau thank you so much! 
Installed it, works and the compose button is back!

fyi, it throws an error though:
<img width="742" alt="Screenshot 2022-06-03 at 13 28 14" src="https://user-images.githubusercontent.com/89066738/171845524-bc619966-e94c-4b49-9ad6-f126da1b508a.png">

**Comment by phicau** [comment]
Another update from my side, please take a look at [https://github.com/team-inbox/inbox-reborn/pull/44#discussion_r895606160](url) for a complete description.

Long story short: if you use uBlock Origin chances are that your compose button is going to disappear. The version in  https://github.com/phicau/inbox-reborn will solve that issue, and as of now it should also work even if you don't use uBlock.

Cheers

**Comment by g60madman** [comment]
@phicau the most current version should be good go now.
