### ISSUE TITLE
Bundles not working.

### ISSUE THREAD

**Issue by theaulddubliner** [team-inbox/inbox-reborn#46]
Hi.

I'm not getting the inbox bundles (I did when I first installed the ext.) and I haven't changed any settings.

I have applied all the recommended settings.

Any ideas?

**Comment by g60madman** [comment]
@theaulddubliner is this still a problem? The bundles seem to be working for me on the current version 0.5.9.10. The new version .11 will show up later today as I posted it to the Chrome Store.

**Comment by awreccan** [comment]
Bundles not working with 0.5.9.11 - just installed today

**Comment by jonrandy** [comment]
> Bundles not working with 0.5.9.11 - just installed today

Can I ask what browser/OS you are using? Do you have the new GMail layout switched on?

**Comment by awreccan** [comment]
@jonrandy Apologies, I reinstalled 0.5.9.11, and it works now on both Chrome and Edge desktop web. Yes I have the new GMail layout switched on.
I'm not sure why it didn't work when I installed the last time. I had the same set of extensions active at both times. Anyway, no matter.

**Comment by jonrandy** [comment]
@g60madman Should we close this?
