### ISSUE TITLE
Suggestion: change theme color

### ISSUE THREAD

**Issue by AkazaRenn** [team-inbox/inbox-reborn#47]
I'm using Gmail as PWA, so it will always have a white title bar above the blue title bar of the app, which doesn't look very good. This should be able to be done by simply doing the code following:
```
var metaTag=document.createElement('meta');
metaTag.name = "theme-color"
metaTag.content = "#1669f1"
document.getElementsByTagName('head')[0].appendChild(metaTag);
```

I'm using a color darker than the app's top bar because Edge believes the original one is "bright" and uses dark texts on it, which doesn't really fit. This one is 15% darker.

**Comment by g60madman** [comment]
Please fork the code and submit it as a pull request.
