### ISSUE TITLE
Bundle categories is not working

### ISSUE THREAD

**Issue by brfranco** [team-inbox/inbox-reborn#56]
The bundle is not working as of today.

**Comment by jonrandy** [comment]
Yup - I can confirm this. I might be able to look this weekend, but am super busy ATM

**Comment by serpentz01** [comment]
Bundle is not working for me as well.  It Began yesterday.   :-(

**Comment by tmenier** [comment]
Glad to see it's not just me. Thanks @jonrandy, your work on this is hugely appreciated!! :)

**Comment by joeytroy** [comment]
@jonrandy I was able to resolve this. Google changed the CSS name for email and I fixed it in the script.js I will push it in a second and send it back to the Google Store.

**Comment by jonrandy** [comment]
Nice. This weekend was looking not great for time to fix it anyway
