### ISSUE TITLE
Email Bundling by labels & Separator between days have stopped working.

### ISSUE THREAD

**Issue by LLI-inc** [team-inbox/inbox-reborn#57]
Hi,

I just noticed tonight that in Chrome, Vivaldi, Brave & Cent browsers that email bundling by labels has stopped working. Also there is no longer any separator between today and yesterday and "earlier" days.

**Comment by LLI-inc** [comment]
Everything back to normal today and working fine. Perhaps I needed to restart my computer.  Weird. Anyway, it's all good now.

**Comment by LLI-inc** [comment]
Everything back to normal today and working fine. Perhaps I needed to restart my computer. Weird. Anyway, it's all good now. But it served to remind me just how much I rely I inbox-reborn and couldn't live without it.

**Comment by joeytroy** [comment]
Looks like it took a minute for Google to approve the extension and it's now showing updated with the fix I added for the bundle. Closing.

**Comment by LLI-inc** [comment]
The bundling and the day separators have stopped for me working again.
