### ISSUE TITLE
Left Sidebar Disappeared after latest update

### ISSUE THREAD

**Issue by LLI-inc** [team-inbox/inbox-reborn#61]
Seems after yesterday's update the left sidebar that includes links to Chat, Spaces & Meet has disappeared.

**Comment by deepfriedfilth** [comment]
That sidebar's layout was a bit broken so I had disabled entirely since I don't particularly use those features, and that got rolled into my last PR. I've spent some time this afternoon styling the sidebar + related functionality, so expect a new PR from me soon after I'm able to test a bit more!

**Comment by LLI-inc** [comment]
Please, take your time. No hurry from me. I just really appreciate the help from you guys!  I never used the sidebar either until some of our clients started using google chat all the time. Now I have to use it.

**Comment by gdubja** [comment]
was the left sidebar ever fixed? i cannot use hangouts/chat any longer and there's no way to force it with the url. thanks!

**Comment by LLI-inc** [comment]
I just saw in the google store that it appears Chat & Meet have been added back in. (See attached screenshot). But, on my updated version (updated 2/10/2023), these aren't appearing for me. Is there some setting I need to adjust to get them to show up?  Thanks so much!!

(Well, for some reason I can't attach a screenshot). 

Anyway, the screenshot just showed that where I see "chat" and "meet" on the chrome store updated version - those aren't showing up on my computer.

**Comment by wellversed** [comment]
> I just saw in the google store that it appears Chat & Meet have been added back in. (See attached screenshot). But, on my updated version (updated 2/10/2023), these aren't appearing for me. Is there some setting I need to adjust to get them to show up? Thanks so much!!
> 
> Well, for some reason I can't attach a screenshot..
> 
> Anyway, the screenshot just showed that where I see "chat" and "meet" on the chrome store updated version - those aren't showing up on my computer.

Same on my end, bumping in hopes we can get this resolved in the PR. I use chat all the time and the separate site is a nuisance.
