### ISSUE TITLE
Reminder not working

### ISSUE THREAD

**Issue by arormoser** [team-inbox/inbox-reborn#67]
Reminder button not working. It only compose email but it doesn't put my email on the To field and it doesn't put Reminder on subject. I get this error when loading:
2script.js:88 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at getMyEmailAddress (script.js:88:45)
    at getEmails (script.js:438:25)
    at updateReminders (script.js:549:30)

**Comment by jonrandy** [comment]
Yeah, I spotted this. It looks like Google have changed the way compose works quite a lot. Hopefully it's fixable

**Comment by jonrandy** [comment]
So, it was easier to fix than I thought (hopefully). I've submitted a PR with the fix - should be merged soon #68

**Comment by arormoser** [comment]
Thank you!!

**Comment by joeytroy** [comment]
I'll try and merge and post tonight to the Chrome Store.

**Comment by jonrandy** [comment]
@arormoser Is it working for you now?

**Comment by joeytroy** [comment]
issue resolved closing.
