### ISSUE TITLE
Label Colors Not Working

### ISSUE THREAD

**Issue by wellversed** [team-inbox/inbox-reborn#73]
Colors for the label icons are not showing up.
![Labels](https://github.com/team-inbox/inbox-reborn/assets/20547257/68be570f-7192-405d-8db3-8cf7894e4e41)

**Comment by jonrandy** [comment]
Hopefully the newly updated version fixes this. Please confirm

**Comment by wellversed** [comment]
Thank you! Yes, this is fixed now.
