### ISSUE TITLE
Auto Collapse the Header

### ISSUE THREAD

**Issue by AbidMHussain** [team-inbox/inbox-reborn#77]
Allow collapsing of the header an left panels, similar to the Simple Gmail Screen (https://chrome.google.com/webstore/detail/simple-gmail-screen/aoadinglmfmhaegojfdbeoljlnjabmkd?hl=en) - right now, I use this in conjunction with Reborn to achieve the auto-hiding of the top search field, which takes up valuable space.

**Comment by joeytroy** [comment]
Since there is another plugin to support this and no one has looked to add this feature I will close this issue.
