### ISSUE TITLE
Hide the Right Side App

### ISSUE THREAD

**Issue by AbidMHussain** [team-inbox/inbox-reborn#78]
Can we have an option to hide the right side app menu? The arrow causes confusion with the compose and reminder buttons, and for those of us that don't use that side panel or those apps, can we just have it permanently hidden?

**Comment by joeytroy** [comment]
@AbidMHussain Sorry for the delay on this can you send a screenshot of what you are talking about in terms of the arrow? I may take a stab at this when I have some more time.

**Comment by joeytroy** [comment]
Closing as no response
