### ISSUE TITLE
White header since the last few days.

### ISSUE THREAD

**Issue by SixParQuatre** [team-inbox/inbox-reborn#80]
It's probably due to some recent changes on Google's part, but the header added by your extension is now white instead of blue; making the search bar and the button to the left of the account button invisible.
This is in Firefox.
![image](https://github.com/team-inbox/inbox-reborn/assets/103901485/0c355d56-c4fb-4766-b8e5-24e45aa93dd2)
![image](https://github.com/team-inbox/inbox-reborn/assets/103901485/65a52fb9-73ba-4cb4-bfcb-1365fb91d314)

**Comment by Flo354** [comment]
Hello,

I have the same issue on latest Chrome version.

Regards,

**Comment by drafie** [comment]
Same issue.

**Comment by joeytroy** [comment]
I pushed the fix to the Google Chrome Store for Edge/Chrome.

@johnrandy Can you update the Firefox plugin?

**Comment by joeytroy** [comment]
All I have fixed the Google Chrome extension it will update or you can download the plugin manually.

@jonrandy can you update Firefox?

**Comment by jonrandy** [comment]
Will do asap, on vacation right now

**Comment by jonrandy** [comment]
Done
