### ISSUE TITLE
Avatars not working

### ISSUE THREAD

**Issue by ovoznyy** [team-inbox/inbox-reborn#81]
it just shows a white circle
I think I saw the avatars when I just enabled the extension a day ago but now it doesn't work
I've tried in incognito mode, still the same

**Comment by joeytroy** [comment]
Can you post a screenshot? I am not seeing anything wrong currently and I am using the newest version of Chrome Version 120.0.6099.110 (Official Build) (64-bit)

**Comment by ovoznyy** [comment]
oh, it is working everywhere, except when there is "in:inbox" search term added
![image](https://github.com/team-inbox/inbox-reborn/assets/5003516/5897b7c7-f254-47da-b116-35ebd2165b20)
![image](https://github.com/team-inbox/inbox-reborn/assets/5003516/120f8cd8-e297-4723-a38a-c5fb2b71046c)

**Comment by deepfriedfilth** [comment]
I noticed this issue recently as well affecting bundle views, which adds "in:inbox label:BUNDLE_NAME" to the search terms.
I have a solution on my fork's dev branch that I will submit a pull request for after a bit more testing!
