### ISSUE TITLE
Bundling b0rked

### ISSUE THREAD

**Issue by deepfriedfilth** [team-inbox/inbox-reborn#9]
Seems as if Google has removed any references to  **.bundle-wrapper** class .
Attempting `document.querySelectorAll(".BltHke[role=main] .bundle-wrapper")` from dev tools console returns an empty nodeList

**Comment by deepfriedfilth** [comment]
Can confirm PR resolves issue in latest Chrome (v84.0.4147.105)

**Comment by g60madman** [comment]
@deepfriedfilth thanks for the fix! Merged it in.
